// Code generated by cmd/reset; DO NOT EDIT.

package storage

func (m *MemStorage) Reset() {
	if m == nil {
		return
	}

	if resetter, ok := interface{}(&m.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	clear(m.gauges)
	clear(m.counters)
}
