package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatalf("failed to get the current working directory: %v", err)
	}

	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		if shouldSkip(path) {
			return filepath.SkipDir
		}
		return processDir(path)
	})
	if err != nil {
		log.Fatalf("failed to walk directory tree: %v", err)
	}
}

func shouldSkip(path string) bool {
	base := filepath.Base(path)
	return base == ".git" || base == "vendor" || base == "testdata"
}

func processDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}

	fset := token.NewFileSet()
	var files []*ast.File
	var pkgName string

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") || name == "reset.gen.go" {
			continue
		}

		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			continue
		}
		files = append(files, f)
		if pkgName == "" {
			pkgName = f.Name.Name
		}
	}

	structs := findResetStructs(files)
	if len(structs) == 0 {
		return nil
	}
	return generateFile(dir, pkgName, structs)
}

type resetStruct struct {
	name   string
	fields []*ast.Field
}

func findResetStructs(files []*ast.File) []resetStruct {
	var result []resetStruct

	for _, file := range files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			if gd.Doc == nil {
				continue
			}

			hasMarker := false
			for _, c := range gd.Doc.List {
				if strings.TrimSpace(c.Text) == "// generate:reset" {
					hasMarker = true
					break
				}
			}
			if !hasMarker {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				result = append(result, resetStruct{
					name:   ts.Name.Name,
					fields: st.Fields.List,
				})
			}
		}
	}
	return result
}

type templateData struct {
	PkgName string
	Structs []templateStruct
}

type templateStruct struct {
	Name     string
	Receiver string
	Fields   []templateField
}

type templateField struct {
	ResetCode string
}

var resetTmpl = template.Must(template.New("reset").Parse(`// Code generated by cmd/reset; DO NOT EDIT.

package {{ .PkgName }}
{{ range .Structs }}
func ({{ .Receiver }} *{{ .Name }}) Reset() {
	if {{ .Receiver }} == nil {
		return
	}
{{ range .Fields }}{{ .ResetCode }}{{ end }}}
{{ end }}`))

func generateFile(dir, pkgName string, structs []resetStruct) error {
	resetStructs := make(map[string]bool)
	for _, s := range structs {
		resetStructs[s.name] = true
	}

	data := templateData{PkgName: pkgName}

	for _, s := range structs {
		receiver := strings.ToLower(s.name[:1])
		ts := templateStruct{
			Name:     s.name,
			Receiver: receiver,
		}

		for _, field := range s.fields {
			for _, name := range field.Names {
				code := buildFieldReset(receiver, name.Name, field.Type, resetStructs)
				ts.Fields = append(ts.Fields, templateField{ResetCode: code})
			}
		}

		data.Structs = append(data.Structs, ts)
	}

	var buf bytes.Buffer
	if err := resetTmpl.Execute(&buf, data); err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
}

func buildFieldReset(recv, fieldName string, expr ast.Expr, resetStructs map[string]bool) string {
	access := recv + "." + fieldName

	switch t := expr.(type) {
	case *ast.Ident:
		if isResetStruct(t.Name, resetStructs) {
			return "\t" + access + ".Reset()\n"
		}
		return "\t" + access + " = " + zeroValue(t.Name) + "\n"

	case *ast.StarExpr:
		var b strings.Builder
		b.WriteString("\tif " + access + " != nil {\n")
		switch inner := t.X.(type) {
		case *ast.Ident:
			if isResetStruct(inner.Name, resetStructs) {
				b.WriteString("\t\t" + access + ".Reset()\n")
			} else {
				b.WriteString("\t\t*" + access + " = " + zeroValue(inner.Name) + "\n")
			}
		case *ast.SelectorExpr:
			b.WriteString("\t\tif resetter, ok := interface{}(" + access + ").(interface{ Reset() }); ok {\n")
			b.WriteString("\t\t\tresetter.Reset()\n")
			b.WriteString("\t\t}\n")
		default:
			b.WriteString("\t\t*" + access + " = " + zeroLiteral(t.X) + "\n")
		}
		b.WriteString("\t}\n")
		return b.String()

	case *ast.ArrayType:
		if t.Len == nil {
			return "\t" + access + " = " + access + "[:0]\n"
		}
		return "\t" + access + " = " + typeString(expr) + "{}\n"

	case *ast.MapType:
		return "\tclear(" + access + ")\n"

	case *ast.SelectorExpr:
		var b strings.Builder
		b.WriteString("\tif resetter, ok := interface{}(&" + access + ").(interface{ Reset() }); ok {\n")
		b.WriteString("\t\tresetter.Reset()\n")
		b.WriteString("\t}\n")
		return b.String()

	case *ast.InterfaceType:
		return "\t" + access + " = nil\n"

	case *ast.FuncType:
		return "\t" + access + " = nil\n"

	case *ast.ChanType:
		return "\t" + access + " = nil\n"

	default:
		return "\t// unsupported type for field " + fieldName + "\n"
	}
}

func isResetStruct(name string, resetStructs map[string]bool) bool {
	return resetStructs[name]
}

func zeroValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune", "uintptr":
		return "0"
	default:
		return typeName + "{}"
	}
}

func zeroLiteral(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return zeroValue(t.Name)
	default:
		return typeString(expr) + "{}"
	}
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return "[" + typeString(t.Len) + "]" + typeString(t.Elt)
	case *ast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	case *ast.BasicLit:
		return t.Value
	default:
		return "any"
	}
}
