package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		if shouldSkip(path) {
			return filepath.SkipDir
		}
		return processDir(path)
	})
	if err != nil {
		log.Fatal(err)
	}
}

func shouldSkip(path string) bool {
	base := filepath.Base(path)
	return base == ".git" || base == "vendor" || base == "testdata"
}

func processDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}

	fset := token.NewFileSet()
	var files []*ast.File
	var pkgName string

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") || name == "reset.gen.go" {
			continue
		}

		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			continue
		}
		files = append(files, f)
		if pkgName == "" {
			pkgName = f.Name.Name
		}
	}

	structs := findResetStructs(files)
	if len(structs) == 0 {
		return nil
	}
	return generateFile(dir, pkgName, structs)
}

type resetStruct struct {
	name   string
	fields []*ast.Field
}

func findResetStructs(files []*ast.File) []resetStruct {
	var result []resetStruct

	for _, file := range files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			if gd.Doc == nil {
				continue
			}

			hasMarker := false
			for _, c := range gd.Doc.List {
				if strings.TrimSpace(c.Text) == "// generate:reset" {
					hasMarker = true
					break
				}
			}
			if !hasMarker {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				result = append(result, resetStruct{
					name:   ts.Name.Name,
					fields: st.Fields.List,
				})
			}
		}
	}
	return result
}

func generateFile(dir, pkgName string, structs []resetStruct) error {
	resetStructs := make(map[string]bool)
	for _, s := range structs {
		resetStructs[s.name] = true
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, s := range structs {
		receiver := strings.ToLower(s.name[:1])
		fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", receiver, s.name)
		fmt.Fprintf(&buf, "\tif %s == nil {\n\t\treturn\n\t}\n\n", receiver)

		for _, field := range s.fields {
			for _, name := range field.Names {
				writeFieldReset(&buf, receiver, name.Name, field.Type, resetStructs)
			}
		}

		fmt.Fprintf(&buf, "}\n\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format %s: %w\nbuffer:\n%s", dir, err, buf.String())
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
}

func writeFieldReset(buf *bytes.Buffer, recv, fieldName string, expr ast.Expr, resetStructs map[string]bool) {
	access := recv + "." + fieldName

	switch t := expr.(type) {
	case *ast.Ident:
		if isResetStruct(t.Name, resetStructs) {
			fmt.Fprintf(buf, "\t%s.Reset()\n", access)
			return
		}
		fmt.Fprintf(buf, "\t%s = %s\n", access, zeroValue(t.Name))

	case *ast.StarExpr:
		fmt.Fprintf(buf, "\tif %s != nil {\n", access)
		switch inner := t.X.(type) {
		case *ast.Ident:
			if isResetStruct(inner.Name, resetStructs) {
				fmt.Fprintf(buf, "\t\t%s.Reset()\n", access)
			} else {
				fmt.Fprintf(buf, "\t\t*%s = %s\n", access, zeroValue(inner.Name))
			}
		case *ast.SelectorExpr:
			fmt.Fprintf(buf, "\t\tif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", access)
			fmt.Fprintf(buf, "\t\t\tresetter.Reset()\n")
			fmt.Fprintf(buf, "\t\t}\n")
		default:
			fmt.Fprintf(buf, "\t\t*%s = %s\n", access, zeroLiteral(t.X))
		}
		fmt.Fprintf(buf, "\t}\n")

	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", access, access)
		} else {
			fmt.Fprintf(buf, "\t%s = %s{}\n", access, typeString(expr))
		}

	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s)\n", access)

	case *ast.SelectorExpr:
		fmt.Fprintf(buf, "\tif resetter, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", access)
		fmt.Fprintf(buf, "\t\tresetter.Reset()\n")
		fmt.Fprintf(buf, "\t}\n")

	case *ast.InterfaceType:
		fmt.Fprintf(buf, "\t%s = nil\n", access)

	case *ast.FuncType:
		fmt.Fprintf(buf, "\t%s = nil\n", access)

	case *ast.ChanType:
		fmt.Fprintf(buf, "\t%s = nil\n", access)

	default:
		fmt.Fprintf(buf, "\t// unsupported type for field %s\n", fieldName)
	}
}

func isResetStruct(name string, resetStructs map[string]bool) bool {
	return resetStructs[name]
}

func zeroValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune", "uintptr":
		return "0"
	default:
		return typeName + "{}"
	}
}

func zeroLiteral(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return zeroValue(t.Name)
	default:
		return typeString(expr) + "{}"
	}
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return fmt.Sprintf("[%s]%s", typeString(t.Len), typeString(t.Elt))
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", typeString(t.Key), typeString(t.Value))
	case *ast.BasicLit:
		return t.Value
	default:
		return "any"
	}
}
