// Code generated by cmd/reset; DO NOT EDIT.

package agent

func (m *MetricsCollector) Reset() {
	if m == nil {
		return
	}

	if resetter, ok := interface{}(&m.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	clear(m.gauges)
	m.pollCount = 0
	m.randomValue = 0
	if m.rand != nil {
		if resetter, ok := interface{}(m.rand).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}

func (g *GopsutilCollector) Reset() {
	if g == nil {
		return
	}

	if resetter, ok := interface{}(&g.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	clear(g.gauges)
	g.cpuNum = 0
}
